AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  SoundFileBaseUrl:
    Type: String
  SoundFileBaseName:
    Type: String
  AppId:
    Type: String
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  serverlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: alexa-sounds-of-rain
      CodeUri: src/handlers
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 60
      Environment:
        Variables:
          TZ: 'Asia/Tokyo'
          SoundFileBaseUrl:
            Ref: SoundFileBaseUrl
          SoundFileBaseName:
            Ref: SoundFileBaseName
          AppId:
            Ref: AppId
          Stage:
            Ref: Stage
